### ISSUE TITLE
An eventless transition is not being rendered.(Always)

### ISSUE THREAD

**Issue by mailok** [statelyai/xstate-viz#232]
An eventless transition is not being rendered. This doesn't just happen in Viz, it happens in components as well.

Example:
```
evaluatingChanges: {
   entry: ["assignChangeToInputValue"],
   always: [
      { target: "waitingForMoreChanges", cond: "isInputValueValid" },
      { target: "idle" }
   ]
 }
```

In the component,`state.value` never gets to render the value: `evaluatingChanges`, however, **the state triggered the entry actions.**

In Viz, you can see the state but you can't see when occurs a transition to it.

Full example: https://codesandbox.io/s/dark-rgb-d1714?file=/src/index.js

This example was also added to the stately registry with the name "AlwaysTransition"

**Comment by davidkpiano** [comment]
This is because going to the `evaluatingChanges` state is a _microstep_ (because it `always` immediately goes to another state) and currently, `machine.transition()` only returns the macrostep (the result of all microsteps).

So this is working by designed, but in v5 we'll give you the ability to listen to microsteps.
